services:
  rss-bridge-youtube:
    image: rss-bridge-youtube:latest
    build: .
    container_name: rss-bridge-youtube
    restart: unless-stopped
    env_file: .env
    logging:
      driver: "json-file"
      options:
        max-size: "100m"
networks:
  default:
    name: rss-bridge-youtube-network
    driver: bridge
